### ISSUE TITLE
关于数据集标注问题

### ISSUE THREAD

**Issue by gengdd** [NNNNerd/mmdet-rgbtdroneperson#1]
作者您好，感谢您优秀的研究工作。最近本人也在研究相关问题，发现我们开源RGBTDronePersion数据集存在标签位置不对的问题。
比如项目页[https://nnnnerd.github.io/RGBTDronePerson/](url)展示的图片。左上角为数据集中01020.jpg，发现bbox存在问题。![image](https://github.com/user-attachments/assets/d2efbfc0-736e-4876-8549-ab39849e7361)
此类问题在数据集的其他图片中也有发现，下图为00007.jpg。
![image](https://github.com/user-attachments/assets/0a832f2f-405e-4430-9cd9-9a2b41b790cc)
不知是本人使用数据集的方式不对，还是本身数据集存在问题，还望您百忙之中核查，感谢。

**Comment by NNNNerd** [comment]
您好！该数据集标注是对于红外图像标注的，红外图像中人体热度显著，因此这一标注流程能够加快标注速度并减轻人力。然而这其中存在的问题是，红外图像与可见光图像并非配准，从而会出现标注对于可见光图像中的目标有偏移的现象，这也是您观察到的问题。这一问题在无人机视角的遥感图像上更为显著，因为相机拍摄范围更大、目标更小。我们这样构造RGBTDronePerson数据集也是为了促进该问题的算法研究。

**Comment by gengdd** [comment]
> 您好！该数据集标注是对于红外图像标注的，红外图像中人体热度显著，因此这一标注流程能够加快标注速度并减轻人力。然而这其中存在的问题是，红外图像与可见光图像并非配准，从而会出现标注对于可见光图像中的目标有偏移的现象，这也是您观察到的问题。这一问题在无人机视角的遥感图像上更为显著，因为相机拍摄范围更大、目标更小。我们这样构造RGBTDronePerson数据集也是为了促进该问题的算法研究。

感谢您的耐心答复，我重新仔细看了下项目页，也有提到，是自己漏看了，感谢！
