### ISSUE TITLE
数据集的谷歌云盘链接无法打开，请问有百度网盘的链接吗

### ISSUE THREAD

**Issue by leileilei2000** [NNNNerd/mmdet-rgbtdroneperson#2]
### Model/Dataset/Scheduler description

数据集的谷歌云盘链接无法打开，请问有百度网盘的链接吗

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by NNNNerd** [comment]
你好！已更新百度网盘链接：
通过百度网盘分享的文件：RGBTDronePerson.zip
链接：https://pan.baidu.com/s/10o8WMPPR7MxhpfgXBMNPQQ?pwd=rr7o 
提取码：rr7o

**Comment by leileilei2000** [comment]
> 你好！已更新百度网盘链接： 通过百度网盘分享的文件：RGBTDronePerson.zip 链接：https://pan.baidu.com/s/10o8WMPPR7MxhpfgXBMNPQQ?pwd=rr7o 提取码：rr7o

十分感谢您的分享！请问另一个VTUAV-det目标检测数据集后续会更新百度网盘链接吗？

**Comment by NNNNerd** [comment]
已更新~
通过百度网盘分享的文件：VTAUV-det
链接：https://pan.baidu.com/s/1-vZh-5qs9JKrqrsP7V0vdA?pwd=j2t2 
提取码：j2t2

**Comment by leileilei2000** [comment]
> 已更新~ 通过百度网盘分享的文件：VTAUV-det 链接：https://pan.baidu.com/s/1-vZh-5qs9JKrqrsP7V0vdA?pwd=j2t2 提取码：j2t2

!!!感谢您的分享！！o(*￣▽￣*)ブ😊
